// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: api/tarus/reporter.proto

package tarus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallbackJudgeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JudgeKey    []byte `protobuf:"bytes,1,opt,name=judge_key,json=judgeKey,proto3" json:"judge_key,omitempty"`
	TimeUse     int64  `protobuf:"varint,101,opt,name=time_use,json=timeUse,proto3" json:"time_use,omitempty"`
	MemoryUse   int64  `protobuf:"varint,102,opt,name=memory_use,json=memoryUse,proto3" json:"memory_use,omitempty"`
	JudgeResult int64  `protobuf:"varint,103,opt,name=judge_result,json=judgeResult,proto3" json:"judge_result,omitempty"`
	Hint        string `protobuf:"bytes,104,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *CallbackJudgeItem) Reset() {
	*x = CallbackJudgeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tarus_reporter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackJudgeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackJudgeItem) ProtoMessage() {}

func (x *CallbackJudgeItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_tarus_reporter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackJudgeItem.ProtoReflect.Descriptor instead.
func (*CallbackJudgeItem) Descriptor() ([]byte, []int) {
	return file_api_tarus_reporter_proto_rawDescGZIP(), []int{0}
}

func (x *CallbackJudgeItem) GetJudgeKey() []byte {
	if x != nil {
		return x.JudgeKey
	}
	return nil
}

func (x *CallbackJudgeItem) GetTimeUse() int64 {
	if x != nil {
		return x.TimeUse
	}
	return 0
}

func (x *CallbackJudgeItem) GetMemoryUse() int64 {
	if x != nil {
		return x.MemoryUse
	}
	return 0
}

func (x *CallbackJudgeItem) GetJudgeResult() int64 {
	if x != nil {
		return x.JudgeResult
	}
	return 0
}

func (x *CallbackJudgeItem) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type CallbackJudgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*CallbackJudgeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CallbackJudgeResponse) Reset() {
	*x = CallbackJudgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_tarus_reporter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallbackJudgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackJudgeResponse) ProtoMessage() {}

func (x *CallbackJudgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tarus_reporter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackJudgeResponse.ProtoReflect.Descriptor instead.
func (*CallbackJudgeResponse) Descriptor() ([]byte, []int) {
	return file_api_tarus_reporter_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackJudgeResponse) GetItems() []*CallbackJudgeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_tarus_reporter_proto protoreflect.FileDescriptor

var file_api_tarus_reporter_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x61, 0x72, 0x75, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x74, 0x61, 0x72, 0x75,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x22, 0xa1,
	0x01, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75, 0x64, 0x67, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x65, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6a,
	0x75, 0x64, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69,
	0x6e, 0x74, 0x22, 0x54, 0x0a, 0x15, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74, 0x61, 0x72,
	0x75, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x78, 0x0a, 0x13, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x12,
	0x61, 0x0a, 0x0d, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75, 0x64, 0x67, 0x65,
	0x12, 0x25, 0x2e, 0x74, 0x61, 0x72, 0x75, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x29, 0x2e, 0x74, 0x61, 0x72, 0x75, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x74, 0x61, 0x72, 0x75, 0x73, 0x2f, 0x3b, 0x74, 0x61, 0x72,
	0x75, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_tarus_reporter_proto_rawDescOnce sync.Once
	file_api_tarus_reporter_proto_rawDescData = file_api_tarus_reporter_proto_rawDesc
)

func file_api_tarus_reporter_proto_rawDescGZIP() []byte {
	file_api_tarus_reporter_proto_rawDescOnce.Do(func() {
		file_api_tarus_reporter_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_tarus_reporter_proto_rawDescData)
	})
	return file_api_tarus_reporter_proto_rawDescData
}

var file_api_tarus_reporter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_tarus_reporter_proto_goTypes = []interface{}{
	(*CallbackJudgeItem)(nil),     // 0: tarus.api.reporter.CallbackJudgeItem
	(*CallbackJudgeResponse)(nil), // 1: tarus.api.reporter.CallbackJudgeResponse
}
var file_api_tarus_reporter_proto_depIdxs = []int32{
	0, // 0: tarus.api.reporter.CallbackJudgeResponse.items:type_name -> tarus.api.reporter.CallbackJudgeItem
	0, // 1: tarus.api.reporter.JudgeResultReporter.CallbackJudge:input_type -> tarus.api.reporter.CallbackJudgeItem
	1, // 2: tarus.api.reporter.JudgeResultReporter.CallbackJudge:output_type -> tarus.api.reporter.CallbackJudgeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_tarus_reporter_proto_init() }
func file_api_tarus_reporter_proto_init() {
	if File_api_tarus_reporter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_tarus_reporter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackJudgeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_tarus_reporter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallbackJudgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_tarus_reporter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tarus_reporter_proto_goTypes,
		DependencyIndexes: file_api_tarus_reporter_proto_depIdxs,
		MessageInfos:      file_api_tarus_reporter_proto_msgTypes,
	}.Build()
	File_api_tarus_reporter_proto = out.File
	file_api_tarus_reporter_proto_rawDesc = nil
	file_api_tarus_reporter_proto_goTypes = nil
	file_api_tarus_reporter_proto_depIdxs = nil
}
