// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tarus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JudgeResultReporterClient is the client API for JudgeResultReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JudgeResultReporterClient interface {
	CallbackJudge(ctx context.Context, in *CallbackJudgeItem, opts ...grpc.CallOption) (*CallbackJudgeResponse, error)
}

type judgeResultReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgeResultReporterClient(cc grpc.ClientConnInterface) JudgeResultReporterClient {
	return &judgeResultReporterClient{cc}
}

func (c *judgeResultReporterClient) CallbackJudge(ctx context.Context, in *CallbackJudgeItem, opts ...grpc.CallOption) (*CallbackJudgeResponse, error) {
	out := new(CallbackJudgeResponse)
	err := c.cc.Invoke(ctx, "/tarus.api.reporter.JudgeResultReporter/CallbackJudge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeResultReporterServer is the server API for JudgeResultReporter service.
// All implementations must embed UnimplementedJudgeResultReporterServer
// for forward compatibility
type JudgeResultReporterServer interface {
	CallbackJudge(context.Context, *CallbackJudgeItem) (*CallbackJudgeResponse, error)
	mustEmbedUnimplementedJudgeResultReporterServer()
}

// UnimplementedJudgeResultReporterServer must be embedded to have forward compatible implementations.
type UnimplementedJudgeResultReporterServer struct {
}

func (UnimplementedJudgeResultReporterServer) CallbackJudge(context.Context, *CallbackJudgeItem) (*CallbackJudgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallbackJudge not implemented")
}
func (UnimplementedJudgeResultReporterServer) mustEmbedUnimplementedJudgeResultReporterServer() {}

// UnsafeJudgeResultReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JudgeResultReporterServer will
// result in compilation errors.
type UnsafeJudgeResultReporterServer interface {
	mustEmbedUnimplementedJudgeResultReporterServer()
}

func RegisterJudgeResultReporterServer(s grpc.ServiceRegistrar, srv JudgeResultReporterServer) {
	s.RegisterService(&JudgeResultReporter_ServiceDesc, srv)
}

func _JudgeResultReporter_CallbackJudge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackJudgeItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeResultReporterServer).CallbackJudge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tarus.api.reporter.JudgeResultReporter/CallbackJudge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeResultReporterServer).CallbackJudge(ctx, req.(*CallbackJudgeItem))
	}
	return interceptor(ctx, in, info, handler)
}

// JudgeResultReporter_ServiceDesc is the grpc.ServiceDesc for JudgeResultReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JudgeResultReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tarus.api.reporter.JudgeResultReporter",
	HandlerType: (*JudgeResultReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallbackJudge",
			Handler:    _JudgeResultReporter_CallbackJudge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tarus/reporter.proto",
}
